# Generated by Django 5.1.1 on 2024-09-13 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_variation_additional_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
