# Generated by Django 5.1.1 on 2024-09-13 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_product_is_featured_product_is_offered_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='count_in_stock',
            new_name='countInStock',
        ),
    ]
